# Generated by Django 3.1 on 2020-08-27 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0009_auto_20200827_2104'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'Фото'},
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'verbose_name': 'Места'},
        ),
        migrations.AlterModelTable(
            name='image',
            table=None,
        ),
        migrations.AlterModelTable(
            name='place',
            table=None,
        ),
    ]
