# Generated by Django 3.1 on 2020-08-27 18:20

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('places', '0010_auto_20200827_2114'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name_plural': 'Фото'},
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'verbose_name_plural': 'Места'},
        ),
    ]
