# Generated by Django 3.1 on 2020-08-29 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0012_image_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['position'], 'verbose_name_plural': 'Фото'},
        ),
        migrations.AlterField(
            model_name='image',
            name='position',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Позиция'),
        ),
    ]
