# Generated by Django 3.1 on 2020-08-30 18:53

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0013_auto_20200829_0856'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'verbose_name_plural': 'Локации'},
        ),
        migrations.AlterField(
            model_name='image',
            name='place',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='places.place', verbose_name='Локация'),
        ),
        migrations.AlterField(
            model_name='place',
            name='description_long',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='place',
            name='description_short',
            field=models.TextField(blank=True, max_length=400, verbose_name='Краткое описание'),
        ),
    ]
